import { FileText, MessageSquare, Sparkles, Zap } from "lucide-react";
import Link from "next/link";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const FEATURES = [
  {
    icon: FileText,
    title: "Transcript extraction",
    description:
      "Paste any YouTube URL and we pull the transcript automatically, translating to English when needed.",
  },
  {
    icon: Sparkles,
    title: "Structured notes",
    description:
      "Get the 5 most important topics and concise, bulleted study notes generated by Gemini 2.5 Flash.",
  },
  {
    icon: MessageSquare,
    title: "Chat with the video",
    description:
      "Ask anything about the video's content — answers are grounded in the transcript via RAG, streamed in real time.",
  },
];

export default function Home() {
  return (
    <div className="mx-auto flex max-w-4xl flex-col items-center gap-16 py-8 text-center">
      <div className="flex flex-col items-center gap-6">
        <div className="flex items-center gap-2 rounded-full border border-border bg-secondary/50 px-4 py-1.5 text-sm text-muted-foreground">
          <Zap className="size-3.5" />
          Powered by Gemini 2.5 Flash + RAG
        </div>
        <h1 className="max-w-2xl text-4xl font-bold tracking-tight sm:text-5xl">
          Turn any YouTube video into notes or a conversation
        </h1>
        <p className="max-w-xl text-lg text-muted-foreground">
          Paste a link, pick a mode, and let Gemini do the reading. Get instant study
          notes or chat directly with the video&apos;s content.
        </p>
        <div className="flex flex-col gap-3 sm:flex-row">
          <Button size="lg" render={<Link href="/chat" />}>
            Get started
          </Button>
          <Button size="lg" variant="outline" render={<Link href="/about" />}>
            Learn more
          </Button>
        </div>
      </div>

      <div className="grid w-full gap-4 sm:grid-cols-3">
        {FEATURES.map((feature) => (
          <Card key={feature.title} className="text-left">
            <CardHeader>
              <feature.icon className="size-6 text-primary" />
              <CardTitle className="mt-2">{feature.title}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">{feature.description}</p>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
